### ISSUE TITLE
Update to latest cordova-plugin-iosrtc

### ISSUE THREAD

**Issue by hthetiot** [apizee/ApiRTC-examples#3]
Guys you still use iosrtc@4 you may want to update to 6.0.11 at some point...
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/CHANGELOG.md#version-6011

**Comment by FredLuart** [comment]
@hthetiot check our sample here with iosRTC 6.0.4 : 
https://github.com/apizee/ApiRTC-mobile/blob/master/package.json

**Comment by hthetiot** [comment]
Last version is 6.0.11, I don't need you example, I'm the maintainer of iosRTC that was just a notice to help you, in any case it does not prevent you to update on this active project the version.

Happy RTC.

**Comment by FredLuart** [comment]
@hthetiot I didn't knew that you were iosRTC maintainer : nice to hear from you !!!
Thanks for the info, we don't update our sample on each iosRTC release but we will check it next time

**Comment by FredLuart** [comment]
iosRTC updated to 6.0.11 : https://github.com/apizee/ApiRTC-mobile
Thanks @hthetiot
